#!/bin/bash

# nome do usuário sislegis
SISLEGIS_USER=sislegis

# quando o ambiente está sendo executando no Vagrant estes 
#   são os diretórios que ficam no HOST (e não na BOX):
SISLEGIS_USER_DIRS=(
.m2
.forge
projetos
sislegis-ambiente.instaladores
)

# nome do arquivo de backup utilizado pelo Vagrant
#   quando são chamados os scripts salvar e restaurar:
VAGRANT_BACKUP_TAR=.vagrant.backup.tar
