#!/bin/bash
# Author: Paulo Jeronimo (email: paulojeronimo@gmail.com, twitter: @paulojeronimo)
set +x

BASEDIR=`cd $(dirname "$0"); echo -n $PWD`
source "$BASEDIR"/config || exit 1

BAIXA_ARQUIVO=`$BAIXA_INSTALADORES && echo -n --baixa-arquivo || echo -n --nao-baixa-arquivo`
X_INSTALADO=`type xhost &> /dev/null && echo -n true || echo -n false`

sudo sed -i '
    s/^\(%sudo.*ALL=\).*/\1\(ALL\) NOPASSWD:ALL/
' /etc/sudoers

f=/etc/vim/vimrc.local
[ -f "$f" ] || { echo "set modeline" | sudo tee $f; }

if [ $USER != vagrant ]
then
    sudo useradd -m -s /bin/bash -G sudo $SISLEGIS_USER &> /dev/null || {
        echo "Falha ao criar usuário $SISLEGIS_USER."
        echo "O ambiente já não está instalado?"
        exit 1
    }

    $X_INSTALADO && {
        cmd="xhost +si:localuser:$SISLEGIS_USER"; $cmd
        f=~/.bashrc; grep -q "xhost.*$SISLEGIS_USER" $f || { echo "$cmd" >> $f; }
    }
else
    SISLEGIS_USER=vagrant
fi

"$BASEDIR"/restaurar

sudo -i -u $SISLEGIS_USER bash <<EOF
executar_e_inserir_no_bashrc() {
    local cmd="\$@"
    eval \$cmd; echo \$cmd >> ~/.bashrc
}

$X_INSTALADO && echo 'export DISPLAY=:0' >> ~/.bashrc

if $USA_PROXY
then
    f="$BASEDIR"/.proxy
    if [ -f "\$f" ]
    then
        cp "\$f" ~/
    else
        echo "Arquivo \"\$f\" não configurado!"
        exit 1
    fi

    executar_e_inserir_no_bashrc "source ~/.proxy"
    executar_e_inserir_no_bashrc "export INSTALA_OPCS+=\" --usa-proxy\""

    f=/etc/apt/apt.conf
    if [ ! -f \$f ] || ! grep -q '^Acquire::http::Proxy' \$f
    then
        cat <<_EOF | sudo tee -a \$f
Acquire::http::Proxy "\$http_proxy";
Acquire::https::Proxy "\$https_proxy";
_EOF
    fi
fi

executar_e_inserir_no_bashrc "export INSTALA_OPCS+=\" $BAIXA_ARQUIVO\""

sudo apt-get install -y tar unzip wget vim software-properties-common git
sudo -E add-apt-repository -y ppa:webupd8team/java
sudo apt-get -y update
sudo apt-get install -y oracle-java8-installer

git clone $GITHUB_SISLEGIS_DOTFILES
${GITHUB_SISLEGIS_DOTFILES##*/}/install

git config --global user.name '$GITHUB_NAME'
git config --global user.email $GITHUB_EMAIL

cat <<_EOF > ~/.projetos
app=$GITHUB_SISLEGIS_APP
site=$GITHUB_SISLEGIS_SITE
_EOF

git clone $GITHUB_SISLEGIS_AMBIENTE
[ \$USER = vagrant ] && { 
    echo 'export PROJETOS_DIR=~/projetos' > ${GITHUB_SISLEGIS_AMBIENTE##*/}/ambiente.config
}
${GITHUB_SISLEGIS_AMBIENTE##*/}/instalar

source .\$(hostname -s)
app_baixar
app_remote_add_upstream
app_update_and_deploy
jboss_start
EOF

# vim: set ts=4 sw=4 expandtab:
