#!/bin/bash
# Author: Paulo Jeronimo (paulojeronimo@gmail.com)
set +x

BASEDIR=`cd $(dirname "$0"); echo -n $PWD`

[ $USER = vagrant ] && {
    cd
    sislegis-dotfiles/remove
    find . -type l -delete
    rm -rf .proxy .projetos .vagrant sislegis-*
    exit
}

"$BASEDIR"/salvar

PIDS=`sudo ps -ef | grep ^sislegis | awk '{print $2}'`
[ "$PIDS" ] && sudo kill -9 $PIDS

sudo userdel -rf sislegis &> /dev/null || {
    echo "Falha ao remover o usuário sislegis."
    echo "O ambiente já não foi removido?"
    exit
}

f=~/.bashrc; e='^xhost.*sislegis$'
grep -q "$e" $f && { grep -v "$e" $f | tee $f > /dev/null; }
