#!/bin/bash
# Author: Paulo Jeronimo (paulojeronimo@gmail.com)
set +x

BASEDIR=`cd $(dirname "$0"); echo -n $PWD`
source "$BASEDIR"/config || exit 1
source "$BASEDIR"/defaults || exit 1

[ $USER = vagrant ] && {
    for d in ${SISLEGIS_USER_DIRS[*]}
    do 
        mkdir -p /sislegis-ambiente-comum/$d
        [ -L $d ] || ln -s /sislegis-ambiente-comum/$d ~/$d
    done
    f=/sislegis-ambiente-comum/"$VAGRANT_BACKUP_TAR"; [ -f "$f" ] && sudo tar xvfP "$f"
    exit
}

grep -q ^$SISLEGIS_USER /etc/passwd || { echo "Usuário $SISLEGIS_USER não existe!"; exit; }
comum="$BASEDIR"/../sislegis-ambiente-comum
if [ -d "$comum" ]
then
    cd "$comum"
    sudo bash <<EOF
for d in ${SISLEGIS_USER_DIRS[*]}
do
    [ \$d = projetos ] && continue
    rsync -av --update \$d ~$SISLEGIS_USER/
    chown -R $SISLEGIS_USER: ~$SISLEGIS_USER/\$d
done
EOF
fi

# vim: set ts=4 sw=4 expandtab:
